In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv(r"..\data\raw\cars_data.csv")
df = df.rename(columns={'kolimeter': 'kilometer', 'feul_type': 'fuel_type'})
df

,name,city,price,model,kilometer,fuel_type,engine,transmission
0,Honda Civic 2021 1.5 RS Turbo for Sale,Abbottabad,PKR 67 lacs,2021,"88,000 km",Petrol,1500 cc,Automatic
1,Honda Civic 2019 Oriel 1.8 i-VTEC CVT for Sale,Peshawar,PKR 61.5 lacs,2019,"68,425 km",Petrol,1800 cc,Automatic
2,Toyota Hilux 2012 D-4D Automatic for Sale,Peshawar,PKR 65.5 lacs,2012,"132,000 km",Diesel,3000 cc,Automatic
3,Toyota Prius Alpha 2018 S Touring Selection G...,Peshawar,PKR 98.5 lacs,2018,"35,000 km",Hybrid,1800 cc,Automatic
4,Toyota Corolla Fielder 2017 Hybrid G WB for...,Peshawar,PKR 62 lacs,2017,"165,044 km",Hybrid,1500 cc,Automatic
...,...,...,...,...,...,...,...,...
4989,Suzuki Cultus 2007 VXR (CNG) for Sale,Mardan,PKR 11.9 lacs,2007,"80,000 km",Petrol,1000 cc,Manual
4990,Suzuki Alto 1998 for Sale,Peshawar,PKR 12.7 lacs,1998,"120,000 km",Petrol,660 cc,Automatic
4991,Suzuki Mehran 2004 VX for Sale,Charsadda,PKR 5.5 lacs,2004,"100,000 km",Petrol,800 cc,Manual
4992,Suzuki Alto 2011 VXR for Sale,Peshawar,PKR 14.99 lacs,2011,"95,000 km",Petrol,1000 cc,Manual
4993,Toyota Corolla 1986 GL Saloon for Sale,Charsadda,PKR 8.8 lacs,1986,"200,000 km",CNG,1500 cc,Manual

In [21]:
df.duplicated().sum()

np.int64(319)

In [22]:
df.drop_duplicates(inplace=True)
df

,name,city,price,model,kilometer,fuel_type,engine,transmission
0,Honda Civic 2021 1.5 RS Turbo for Sale,Abbottabad,PKR 67 lacs,2021,"88,000 km",Petrol,1500 cc,Automatic
1,Honda Civic 2019 Oriel 1.8 i-VTEC CVT for Sale,Peshawar,PKR 61.5 lacs,2019,"68,425 km",Petrol,1800 cc,Automatic
2,Toyota Hilux 2012 D-4D Automatic for Sale,Peshawar,PKR 65.5 lacs,2012,"132,000 km",Diesel,3000 cc,Automatic
3,Toyota Prius Alpha 2018 S Touring Selection G...,Peshawar,PKR 98.5 lacs,2018,"35,000 km",Hybrid,1800 cc,Automatic
4,Toyota Corolla Fielder 2017 Hybrid G WB for...,Peshawar,PKR 62 lacs,2017,"165,044 km",Hybrid,1500 cc,Automatic
...,...,...,...,...,...,...,...,...
4989,Suzuki Cultus 2007 VXR (CNG) for Sale,Mardan,PKR 11.9 lacs,2007,"80,000 km",Petrol,1000 cc,Manual
4990,Suzuki Alto 1998 for Sale,Peshawar,PKR 12.7 lacs,1998,"120,000 km",Petrol,660 cc,Automatic
4991,Suzuki Mehran 2004 VX for Sale,Charsadda,PKR 5.5 lacs,2004,"100,000 km",Petrol,800 cc,Manual
4992,Suzuki Alto 2011 VXR for Sale,Peshawar,PKR 14.99 lacs,2011,"95,000 km",Petrol,1000 cc,Manual
4993,Toyota Corolla 1986 GL Saloon for Sale,Charsadda,PKR 8.8 lacs,1986,"200,000 km",CNG,1500 cc,Manual

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 4675 entries, 0 to 4993
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          4675 non-null   str
 1   city          4675 non-null   str
 2   price         4675 non-null   str
 3   model         4675 non-null   int64
 4   kilometer     4675 non-null   str
 5   fuel_type     4675 non-null   str
 6   engine        4675 non-null   str
 7   transmission  4675 non-null   str
dtypes: int64(1), str(7)
memory usage: 328.7 KB

In [24]:
df['city'] = df['city'].str.lower().str.strip()
df.value_counts('city').sort_index()

city
abbottabad           618
akora khattak         12
balakot                3
bannu                 45
bat khela             12
buner                 11
charsadda            116
dargai                 4
darya khan             5
dera ismail khan     114
dir                    3
gari habibullah        1
ghazi                  6
gohar ghoushti         1
haripur              227
hattar                 2
hawilian               5
hayatabad              5
jamrud road            1
jehangira              3
karak                 28
kohat                109
lakki marwat           7
lower dir             14
malakand agency       19
mansehra             280
mardan               413
mingora                8
nowshera             131
nowshera cantt        45
peshawar            2107
qalandarabad           4
risalpur              21
saidu sharif           1
swabi                219
swat                  28
swatmingora           16
takhtbai              17
tank                   1
topi                  13
Name: count, dtype: int64

In [25]:
df['price'] = (
    df['price']
    .str.replace(r'[^0-9.]', '', regex=True)
)

df['price'] = pd.to_numeric(df['price'])* 100000

In [26]:
df

,name,city,price,model,kilometer,fuel_type,engine,transmission
0,Honda Civic 2021 1.5 RS Turbo for Sale,abbottabad,6700000.0,2021,"88,000 km",Petrol,1500 cc,Automatic
1,Honda Civic 2019 Oriel 1.8 i-VTEC CVT for Sale,peshawar,6150000.0,2019,"68,425 km",Petrol,1800 cc,Automatic
2,Toyota Hilux 2012 D-4D Automatic for Sale,peshawar,6550000.0,2012,"132,000 km",Diesel,3000 cc,Automatic
3,Toyota Prius Alpha 2018 S Touring Selection G...,peshawar,9850000.0,2018,"35,000 km",Hybrid,1800 cc,Automatic
4,Toyota Corolla Fielder 2017 Hybrid G WB for...,peshawar,6200000.0,2017,"165,044 km",Hybrid,1500 cc,Automatic
...,...,...,...,...,...,...,...,...
4989,Suzuki Cultus 2007 VXR (CNG) for Sale,mardan,1190000.0,2007,"80,000 km",Petrol,1000 cc,Manual
4990,Suzuki Alto 1998 for Sale,peshawar,1270000.0,1998,"120,000 km",Petrol,660 cc,Automatic
4991,Suzuki Mehran 2004 VX for Sale,charsadda,550000.0,2004,"100,000 km",Petrol,800 cc,Manual
4992,Suzuki Alto 2011 VXR for Sale,peshawar,1499000.0,2011,"95,000 km",Petrol,1000 cc,Manual
4993,Toyota Corolla 1986 GL Saloon for Sale,charsadda,880000.0,1986,"200,000 km",CNG,1500 cc,Manual

In [27]:
df['price'].isna().sum()

np.int64(1)

In [28]:
df['kilometer'] = (
    df['kilometer']
    .str.replace(r'[^0-9]', '', regex=True)
)
df['kilometer'] = pd.to_numeric(df['kilometer'])

In [29]:
df['engine'] = (
    df['engine']
    .str.replace(r'[^0-9]', '', regex=True)
)
df['engine'] = pd.to_numeric(df['engine'])

In [30]:
df["fuel_type"]=df["fuel_type"].str.lower()
df["fuel_type"].value_counts()

fuel_type
petrol      3793
hybrid       397
cng          266
diesel       205
lpg            8
phev           3
electric       3
Name: count, dtype: int64

In [31]:
df["fuel_type"].str.replace("lp","cng")

0       petrol
1       petrol
2       diesel
3       hybrid
4       hybrid
         ...
4989    petrol
4990    petrol
4991    petrol
4992    petrol
4993       cng
Name: fuel_type, Length: 4675, dtype: str

In [32]:
df["transmission"]=df["transmission"].str.lower()
df["transmission"].value_counts()

transmission
automatic    2400
manual       2272
dht             3
Name: count, dtype: int64

In [33]:
df['brand'] = df['name'].str.lower().str.split().str[0]

In [34]:
df['brand'].value_counts()

brand
toyota        1977
suzuki        1494
honda          678
daihatsu       141
nissan         101
kia             45
mitsubishi      42
hyundai         29
mercedes        26
haval           21
mazda           16
changan         16
mg              15
jeep            10
faw              9
dfsk             6
daewoo           5
prince           5
peugeot          4
united           4
subaru           4
bmw              3
land             3
datsun           2
baic             2
jac              2
isuzu            2
chevrolet        2
lexus            1
gmc              1
range            1
rinco            1
dodge            1
proton           1
chery            1
jw               1
adam             1
audi             1
hino             1
Name: count, dtype: int64

In [35]:
df['name'] = (
    df['name']
    .str.replace(r'\d{4}', '', regex=True)        # remove year
    .str.replace('for Sale', '', regex=False)     # remove noise text
    .str.replace(r'\s+', ' ', regex=True)         # remove extra spaces
    .str.strip()
    .str.split()
    .str.join(' ')
)

In [36]:
df

,name,city,price,model,kilometer,fuel_type,engine,transmission,brand
0,Honda Civic 1.5 RS Turbo,abbottabad,6700000.0,2021,88000,petrol,1500,automatic,honda
1,Honda Civic Oriel 1.8 i-VTEC CVT,peshawar,6150000.0,2019,68425,petrol,1800,automatic,honda
2,Toyota Hilux D-4D Automatic,peshawar,6550000.0,2012,132000,diesel,3000,automatic,toyota
3,Toyota Prius Alpha S Touring Selection GR Sport,peshawar,9850000.0,2018,35000,hybrid,1800,automatic,toyota
4,Toyota Corolla Fielder Hybrid G WB,peshawar,6200000.0,2017,165044,hybrid,1500,automatic,toyota
...,...,...,...,...,...,...,...,...,...
4989,Suzuki Cultus VXR (CNG),mardan,1190000.0,2007,80000,petrol,1000,manual,suzuki
4990,Suzuki Alto,peshawar,1270000.0,1998,120000,petrol,660,automatic,suzuki
4991,Suzuki Mehran VX,charsadda,550000.0,2004,100000,petrol,800,manual,suzuki
4992,Suzuki Alto VXR,peshawar,1499000.0,2011,95000,petrol,1000,manual,suzuki
4993,Toyota Corolla GL Saloon,charsadda,880000.0,1986,200000,cng,1500,manual,toyota

In [37]:
df.to_csv('../data/interim/cars_cleaned.csv', index=False)